### ISSUE TITLE
No way to access mailchimps validation

### ISSUE THREAD

**Issue by SethArchambault** [Sammaye/mailchimp#2]
Right now all error messages are shoved into a string, making it impossible to use for validation back to the user.

**Comment by Sammaye** [comment]
You mean the `errors` array? I was thinking on how to do that. I will come up with something

**Comment by Sammaye** [comment]
Try that https://github.com/Sammaye/mailchimp/commit/8515c6eea1d2b39a94187cc326262eba6632f188

**Comment by Sammaye** [comment]
Oh the errors should be accessible as `->errors` on the exception
