### ISSUE TITLE
Wrong file name for MethodNotAllowedException

### ISSUE THREAD

**Issue by B-Prod** [Sammaye/mailchimp#4]
The file name for the class "MethodNotAllowedException" is wrong, there is a spelling mistake that makes the class to not be found...

MetodNotAllowedException.php

There is a missing "h"

**Comment by Sammaye** [comment]
Done and released to 1.4.1 thanks

**Comment by B-Prod** [comment]
OK, I created a pull request, but you were too quick to fix this ;-)

Thanks for your reactivity
